MCU = atmega32u4

BOOTLOADER = atmel-dfu

BOOTMAGIC_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CONSOLE_ENABLE = no
COMMAND_ENABLE = no
NKRO_ENABLE = yes
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
AUDIO_ENABLE = no
RGB_MATRIX_ENABLE = yes
RGB_MATRIX_DRIVER = IS31FL3731

LAYOUTS = 65_ansi